### ISSUE TITLE
texlive-lang-czechslovak dependencies issue

### ISSUE THREAD

**Issue by mbudaj** [debian-tex/texlive-nonbin#2]
Since Debian Bullseye the package texlive-lang-czechslovak [depends on](https://packages.debian.org/bullseye/texlive-lang-czechslovak) and thus requires to install many other languages (like Polish, Spanish, French). This hugely increases the required download size and disk space. For other languages, such cross-dependency is not the case.

**Comment by hpreusse** [comment]
Please note that we use github for hosting our development files, but we use the Debian bug tracking system for bug reporting. Please use that system.
We had to introduce these many deps to make sure the format files are build correctly. See [this link](https://bugs.debian.org/928805) for details.

**Comment by mbudaj** [comment]
That makes it clear, thanks.
